name: musickvv-bot
services:
  - name: bot
    type: web
    runtime: python
    build:
      commands:
        - pip install -r requirements.txt
    env:
      - key: BOT_TOKEN
        value: "8484157544:AAH-VnpqojEVo3_obfOCDXULZ1sGXUTIYQs"
    run:
      command: python bot.py
